#!/bin/bash

# Raspberry Pi SoC (CPU) temperature monitor plugin for Munin
# Copyright (c) 2017 David King
# https://github.com/strix-technica/ADSB-tools
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

case $1 in
   config)
        cat <<'EOM'
graph_title System-on-Chip temperature
graph_vlabel °C
graph_category system
temp.label Temperature
EOM
        exit 0;;
esac

temp=$(cat /sys/class/thermal/thermal_zone0/temp)
echo temp.value ${temp:0: -3}.${temp: -3}
